version: '3'
services:
  
  db:
    build: .
    image: postgres:14.2-alpine
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 5433:5432

volumes:
  db:
  redis:
